name: flutter_markdown_editor
description: A package for markdown editor widget, you can use pre-exist editors or customize the view to build yours.
version: 0.0.2
homepage: https://github.com/ammaratef45/flutter_markdown_editor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.4.4
  markdown: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: